### ISSUE TITLE
Implement Analyzing Methods

### ISSUE THREAD

**Issue by jussi-kalliokoski** [jussi-kalliokoski/audiolib.js#10]
Such as fourier methods, etc. See js/process/fourier.js for the unfinished work with that.

**Comment by davidgovea** [comment]
Getting some incorrect results:
Input signal is a single 600Hz Sine, no filters applied
Red is dsp.js, blue is audiolib fft
![FFT image](http://i56.tinypic.com/2j5gcjb.png)

test version is here if you want to replicate: 5f88e788330862ac3d63 (be sure to include dsp.js)

**Comment by jussi-kalliokoski** [comment]
Looks like the phase goes off somewhere, producing some extra harmonics... Meh.

**Comment by jussi-kalliokoski** [comment]
Going to use a separate library, [fft.js](https://github.com/jussi-kalliokoski/fft.js) dedicated for really fast FT. Integrating soon.

**Comment by jussi-kalliokoski** [comment]
Integrated, now I just have to implement some window functions, and all that, but that's pretty easy stuff.

**Comment by jussi-kalliokoski** [comment]
The FFT was the blocking issue for v.0.5 so removing this from the milestone, although it's still a valid issue, need more analyzing methods.

**Comment by jussi-kalliokoski** [comment]
Closing this as adding more analyzers is not in my plan right now
