### ISSUE TITLE
Static ADSR Envelope generation

### ISSUE THREAD

**Issue by davidgovea** [jussi-kalliokoski/audiolib.js#24]
While using buffer generation synthesis techniques, it would be handy to be able to generate static ADSR envelopes without having to trigger the gate open/closed.  Does that make it an ADR envelope? :P

The current implementation is more geared toward live interaction like Orbisyn

Maybe the Envelope class could be an effect, using .append to apply an envelope to a buffer. On the other hand, .generate could be used.. `osc.addPreProcessing(function(){ adsr.generate(); this.mix = adsr.getMix(); })`

**Comment by jussi-kalliokoski** [comment]
You're right. Hmm...

I should probably make things previously labeled as "controls" (ADSR, Step Seq) behave as generators as well, would make sense to integrate with all the new functionality.

Maybe then, one could use the `generateBuffer` I just added? :P

**Comment by jussi-kalliokoski** [comment]
I think we have this functionality now. :P

**Comment by davidgovea** [comment]
Hmm, still looks like you have to trigger the gate closed to get into the release stage. I could be missing something...

**Comment by davidgovea** [comment]
Looking goood...
