### ISSUE TITLE
More specs & review

### ISSUE THREAD

**Issue by jussi-kalliokoski** [jussi-kalliokoski/audiolib.js#3]
Currently there is only a spec for CODEC plugins, more specs should be created (and implemented, if not already). Also the existing specs are somewhat vague. This would make it much easier for people to learn to use, adopt and develop for audiolib.js.

**Comment by davidgovea** [comment]
Great job on the spec updates - they're well thought out. Was sad to see no collaboration in here - I'm planning to use audiolib in my node KO entry and am interested in contributing.  Keep it up!

**Comment by jussi-kalliokoski** [comment]
Thanks, that's great!!  There's going to be some change to the contributing as well, as ofmlabs is taking audiolib.js under its wing, I think you'll like that piece of news!

**Comment by davidgovea** [comment]
## The problem

Certain effects respond differently to multi-channel interleaved signals (filters, delays, etc), so we may want to think about making it more convenient to process multiple channels at once.
This is handled automatically when using the Buffered Effect approach (duplicates effect for each channel), but it's a little more confusing when using pushSample.

Currently, I am using:

``` javascript
var sampler = new audioLib.Sampler(sampleRate),
    lpf = [
        new audioLib.BiquadFilter.LowPass(sampleRate, 1200, 0.6), 
        new audioLib.BiquadFilter.LowPass(sampleRate, 1200, 0.6)
    ];


// inside fillBuffer:
for (i=0; i<l; i+=channelCount){
    sampler.generate();
    for (n=0; n<channelCount; n++){
        buffer[n + i] = lpf[n].pushSample(sampler.getMix(n));
    }
}
```

## Possible way to make this easier:

Create a `.toStereo()` or `.toChannels(n)` method which clones the filter and allows each to be accessed by `.pushSample(sample, n)` and `.getMix(n)`

``` javascript
var lpf = new audioLib.BiquadFilter.LowPass(sampleRate, 1200, 0.6).toStereo();

// fill buffer like above:
buffer[n + i] = lpf.pushSample(sampler.getMix(n), n);
```

This is similar to the .join method creating EffectChains.. In fact, something parallel would be good for setting different parameters to each channel (like Freeverb):

``` javascript
var reverb = new audioLib.Freeverb(sampleRate).stereoJoin(new audioLib.Freeverb(sampleRate, right_channel_true));

// fill buffer like above:
buffer[n + i] = reverb.pushSample(sampler.getMix(n), n);
```

## An alternative:

We could allow effects to be multi-channel, and take the optional channel parameter in pushSample and getMix.  This would require changing the spec and re-writing the affected effects to include a channelCount parameter in the constructor.  The effect would then create a buffer for each channel.

Effects not affected by this include the bitcrusher, compressor, maybe more.

**Comment by jussi-kalliokoski** [comment]
This is something I've been losing my sleep to lately... :D

Maybe effects that require multi-channel behaviour should be specced & behave differently. It's a bit inconsistent, but I think it might be the best way to do it. E.g,

```

MultiChannelEffect
{

      append(buffer, channelCount);
      pushSamples(Array samples);
}

```

maybe an example would work better:

```

var x = new audioLib.Panner(0.5)
x.pushSamples([left, right])

```

But I like your idea more, it makes more sense to send the channel number to the effect. But for those effects, one should probably explicitly ask for getMix after all samples have been pushed, because for example a Panner will not know the result of the left channel if it hasn't been told the right channel too. This would also make it easy for the behaviour to be made transparent in abstractions.

However, in your case you could just do something like this:

```

var lpf = new audioLib.LP12Filter/* I just realized you can't do BiquadFilter.LowPass.createBufferBased(), which probably needs to be fixed. */.createBufferBased(2, sampleRate, 1200, 3.2);
buffer[n + i] = lpf.effects[n].pushSample(sampler.getMix(n));

```

Needs more thought.

**Comment by jussi-kalliokoski** [comment]
I changed the BiquadFilter code a bit to make it possible to createBufferBased, and hmm, had to tamper with the design a bit, sorry. https://github.com/jussi-kalliokoski/audiolib.js/commit/9abbaff0c7c395afb8b3a5c4c35bf998bc316dbb

**Comment by jussi-kalliokoski** [comment]
Closing this issue as it's inactive.
