### ISSUE TITLE
Error in \audiolib\tests\node-record.js 

### ISSUE THREAD

**Issue by bersy** [jussi-kalliokoski/audiolib.js#34]
ReferenceError: window is not defined
    at Function.doInterval (d:\Server\node.js\audiolib\lib\audiolib.js:2416:20)

This line (audiolib.js:2416):
var BlobBuilder = window.MozBlobBuilder || window.WebKitBlobBuilder || window.MSBlobBuilder || window.OBlobBuilder || window.BlobBuilder,
        timer, id, prev;

node.js 0.5.6 binary for Windows OS

**Comment by jussi-kalliokoski** [comment]
Thanks for reporting!

It should work now, force update via npm and you're good to go!
