### ISSUE TITLE
Can you determine volume x time on a per-channel basis with this lib?

### ISSUE THREAD

**Issue by bingomanatee** [jussi-kalliokoski/audiolib.js#35]
I need to graph audio over time for a sample of MP3 data (stereo) - can you get the data from MP3 files/streams with this lib?

**Comment by davidgovea** [comment]
I've never loaded in an mp3 sample - you might be able to do it with [jsmad](https://github.com/nddrylliog/jsmad).. but keep an eye on [mp3.js](https://github.com/nddrylliog/mp3.js) and [aurora.js](https://github.com/JensNockert/aurora.js) (still in development) for this functionality.

Assuming you can convert your MP3's to WAVs.. then yes audiolib.js can be used to create waveform graphs.  
You have access to the PCM stream sample-by-sample (floats -1 to +1) once you've loaded the audio clip.

To assemble the waveform display graph, you'll need to group the samples into frames (one frame will result in one graph data point), find the min/max values of the PCM stream within each frame.
[here's](http://blog.efnx.com/?p=75) a nice little article on this.

Don't have time to go into crazy detail right now, but to recap:
1) create new audiolib.Sampler()
2) load WAV data in
3) fire sample with sampler.noteOn
4) get channel data with sampler.getMix(channelNumber)
5) progress to the next sample with sampler.generate()
6) repeat 4-5 n times, where n = length of the wav in samples

Some of the test files that use the sampler will be helpful to look at.  Also, I can write a more detailed description or maybe a little demo if it would help you out - just let me know.

**Comment by jussi-kalliokoski** [comment]
This functionality will not be a part of this library. Closing.
