### ISSUE TITLE
License: MIT -> BSD

### ISSUE THREAD

**Issue by jussi-kalliokoski** [jussi-kalliokoski/audiolib.js#45]
As BSD has been chosen as the preferred license for Official.fm Labs projects, this change will be enforced after this month (on 1st of March 2012), unless contributors have any objections.

**Comment by jussi-kalliokoski** [comment]
Ping @davidgovea

**Comment by jussi-kalliokoski** [comment]
Ping @kindohm as well because now there's your code in here as well. :)

**Comment by kindohm** [comment]
Which BSD license (e.g. 4-clause, 3-clause, or 2-clause)?

**Comment by jussi-kalliokoski** [comment]
3-clause. :)

**Comment by kindohm** [comment]
No objections here.

**Comment by davidgovea** [comment]
little late to the party, but no objections here!

ramping up for the next project..

**Comment by jussi-kalliokoski** [comment]
Great, I guess it's decided then. :) Now, to execute... Silly licenses.

**Comment by jussi-kalliokoski** [comment]
This project is no longer directed by ofmlabs, hence this is no longer required and I prefer MIT anyway. Closing.
