### ISSUE TITLE
Creating Float32Array from existing data [#,#,#]

### ISSUE THREAD

**Issue by ewdicus** [jussi-kalliokoski/audiolib.js#49]
Hello,

Sorry to file this as an issue, but I'm unsure of where else to get the information. I have a JS array of floating point numbers between -1 and 1 that I'd like to play back. How do I format this as a Float32Array to do so?

Thanks

P.S. I looked to no avail, but is there a mailing list where we can ask more general questions?

**Comment by jussi-kalliokoski** [comment]
Hey there,

``` javascript
new Float32Array([1.0, -1.0]);
```

Should do the trick! :)

Cheers,
Jussi

**Comment by ewdicus** [comment]
Hi Jussi,

Thanks, that works just fine. Is the creation of that object asynchronous? I've included an example of what I'm trying to do below.

I get a buffer full of audio from a plugin and then try to play it. If I set a breakpoint on dev.writeBuffer, and wait a sec I hear the audio when I continue. However, without the breakpoint I hear nothing.

``` javascript
    dev = audioLib.Sink(null, 1);

    function play(){
        var buffArray = plugin().getBuffer();
        var buff = new audioLib.Float32Array(buffArray);
        dev.writeBuffer(buff); /*set a breakpoint on this line */
    }
```

Thanks for the quick response and the library.

**Comment by jussi-kalliokoski** [comment]
Hey,

The Typed Array creation is not asynchronous, that's odd... There may be a bug in sink.js, but I doubt it, however, I'll check it out tomorrow. However, FYI the `writeBuffer()` method is semi-asynchronous, but that shouldn't affect your case.

My first impression is that the memory allocation takes a while and blocks long enough for something weird to happen, but I don't know why that would affect the case either. How long is the buffer?

I'll get back to this tomorrow. :)

**Comment by ewdicus** [comment]
Thanks for taking a look. It's a single channel buffer at 44100. I've tried
various lengths all less than 5 seconds; so less than 220,500 samples.

Thanks again.

On Fri, Mar 2, 2012 at 10:44 AM, Jussi Kalliokoski <
reply@reply.github.com

**Comment by jussi-kalliokoski** [comment]
Ok, I ran the tests (I changed my mind about tomorrow, heh), `writeBuffer()` is definitely working as expected.

However, a few problems that should cause your buffer to be at least played back incorrectly:

1) It's mono, it's highly likely that your `Sink` instance is stereo, and writeBuffer()`doesn't handle any conversion.
2) The`Sink`instance may not be of the correct sample rate, and not`writeBuffer()``` doesn't handle conversion on that end either.

This is a limitation due to the fact that `writeBuffer()` is a low level method, optimized for performance.

So for your 44.1kHz mono track, you'll have to be a bit explicit about your intentions here:

``` javascript
var convertedBuff = Sink.resample(buff, 44100, dev.sampleRate);
var channels = [];
while (channels.length < dev.channelCount) {
  channels.push(convertedBuff);
}
dev.writeBuffer(Sink.interleave(channels, dev.channelCount));
```

Note that the resampling algorithms packaged in sink.js are quite naive, and not very flexible, i.e. unusable for continuous-time resampling. This is issue is being fixed by [src.js](https://github.com/jussi-kalliokoski/src.js) (WIP).

However, what I just described doesn't fix that you aren't hearing any sound at all, so back to the problem.

The length of the buffers: a megabyte is huge in JS, and it might take some time allocating the buffer. What browser are you trying on and what action triggers the `play()`? This sounds like something that might happen in Chrome.

**Comment by ewdicus** [comment]
I am using Chrome. I'll test in FF as well. play() is just triggered by a link on the page.

I thought that by calling `javascript audioLib.Sink(null, 1);` I was asking it to be one channel at 44100. (Though I suppose I need to check that it's actually using that sample rate.)  So why the re-sampling?

Thanks again, I really appreciate it.

**Comment by jussi-kalliokoski** [comment]
> I thought that by calling javascript audioLib.Sink(null, 1); I was asking it to be one channel at 44100. (Though I suppose I need to check that it's actually using that sample rate.) So why the re-sampling?

Good question. The current implementation of the Web Audio API doesn't allow you to decide the sample rate, nor the channel count, hence you're requesting a sample rate, but not necessarily getting what you want. On Firefox, however, you should almost always get what you want. Ideally, sink.js would handle the resampling automatically with the Web Audio API as well, but because of the non-continuous nature of the built-in resampling methods in sink.js, this will be possible only after src.js is ready for use.

Let me know if it works in Firefox, and I'll try to cook up a solution.

**Comment by ewdicus** [comment]
Oddly enough, I get no sound at all in Firefox, even with the breakpoint. I did check the sample rate on both and I see what you mean about that.

**Comment by jussi-kalliokoski** [comment]
All right then, this time I'll actually pass this until tomorrow, too tired to see anything meaningful in this given data, heh.

**Comment by jussi-kalliokoski** [comment]
I tried some stuff and even buffers as long as a minute seem to be playing back just fine (except for the about 1 sec allocation time on Chrome):

``` javascript
Sink().on('ready', function () {
    var x = new Float32Array(this.sampleRate * this.channelCount * 60);
    audioLib.Oscillator(this.sampleRate).append(x, this.channelCount);
    this.writeBuffer(x);
});
```

So, I don't know if I can figure out the problem from the information I have. I strongly believe that the given data may be faulty. Maybe you could link me the source? If you want to keep it secret, you can just send me a link on a personal message, so I can take a quick look and see if I can figure out what's wrong.

**Comment by ewdicus** [comment]
Well, your example works fine, so I'm not sure either; Though that certainly points to something strange on my end. I've fixed the sampling issue and all works as expected in Chrome. Firefox is still being a pain, and that's the oddity to me.

I'll re-check my data, perhaps there's something I've missed. Thanks for the the insight. I'll let you know if I find the culprit or have any revelations.
