### ISSUE TITLE
best way to stop playing audio

### ISSUE THREAD

**Issue by kindohm** [jussi-kalliokoski/audiolib.js#50]
What is the best way to stop (either temporarily or permanently) playing audio? So far in my code I've used something like this:

``` javascript
var callback = audioCallback(buffer, channels) {
    if (playing) {
        osc.append(buffer, channels);
    }
};

$(button).click(function () { playing = !playing; }
```

Is there a better or more formal way to stop the audio? With this method, audioCallback will always be called - the implementation is just bypassed.

**Comment by jussi-kalliokoski** [comment]
You can destroy a `Sink` instance with the `sinkInstance.kill()` method. This will stop all the callbacks, etc. However, that means you have to create a new Sink if you want to continue playback.
