### ISSUE TITLE
Multiple Oscillator Instances

### ISSUE THREAD

**Issue by redned** [jussi-kalliokoski/audiolib.js#51]
Multiple oscillator objects seem to output uneven sound.

I wanted to create a one octave bass synth using one oscillator instance for each note, which is playable via a MIDI keyboard. This would allow me to pass a frequency to an oscillator when a note-on message is received and then a null frequency to the same oscillator object when a note-off message is received. 

From playing with the code it seems to start bugging out after I introduce more than one oscillator. It seems that pulling bytes from more than one oscillator at the same time is a little too much. The more oscillators there is the crazier the sound output is, so using 12 is not going to work.

**Comment by jussi-kalliokoski** [comment]
12 oscillators should be just fine, and not even too serious for the CPU.

I could probably help more if you showed some code. :) However, this might be a relevant code example for you: http://labs.avd.io/synth/

**Comment by redned** [comment]
Hi, I was unsure how to enter code neatly in this comment box. To make it easier for you to read it can be found at the link below.
http://dl.dropbox.com/u/2107026/bass.js

Please excuse the primitive code in the link, I am new to programming. 

Oscillators and effects are created in the onload method and sent to the buffer with the effects in the fillbuffer method.

MidiBridge is used to receive the note-on and note-off messages as well as the note name. These are then fed into 
the oscillator object when key is pressed and the oscillator is fed a null frequency when the key is released. This is done individually for each note. 

The sound output however, is very inconsistent in both volume and sound.

**Comment by jussi-kalliokoski** [comment]
This will probably get you fixed up:

``` javascript
                for (n+=0; n<channelCount; n++)
                {   
                        buffer[i + n] += fx.pushSample(smpl1);
                        buffer[i + n] += fx.pushSample(smpl2);
                        buffer[i + n] += fx.pushSample(smpl3);
                        buffer[i + n] += fx.pushSample(smpl4);
                        buffer[i + n] += fx.pushSample(smpl5);
                        buffer[i + n] += fx.pushSample(smpl6);
                        buffer[i + n] += fx.pushSample(smpl7);
                        buffer[i + n] += fx.pushSample(smpl8);
                        buffer[i + n] += fx.pushSample(smpl9);
                        buffer[i + n] += fx.pushSample(smpl10);
                        buffer[i + n] += fx.pushSample(smpl11);
                        buffer[i + n] += fx.pushSample(smpl12);
                }
```

But you might want to change it up a bit to group the assignments and to need less variables. Also using the push sample for each oscillators output will lead to funny things, so I suggest refactoring:

``` javascript
        var     l       = buffer.length, env,
                smpl,
                i, n, out, out2, out3, out4;
        for (i=0; i<l; i+=channelCount)
        {
                volENV.generate();
                lfo1.generate();//LFO generated
                lfo1.waveShape = 'triangle';

                osc1.fm = osc2.fm = osc3.fm = osc4.fm = osc5.fm = osc6.fm =
                osc7.fm = osc8.fm = osc9.fm = osc10.fm = osc11.fm = osc12.fm =
                        lfo1.getMix() * 0.2;


                env *= 0.2 * volENV.value;


                smpl = osc1.getMix() + osc2.getMix() + osc3.getMix() +
                        osc4.getMix() + osc5.getMix() + osc6.getMix() +
                        osc7.getMix() + osc8.getMix() + osc9.getMix() +
                        osc10.getMix() + osc11.getMix() + osc12.getMix();


                fx.pushSample(smpl);
                smpl = fx.getMix();

                for (n=0; n<channelCount; n++)
                {
                        buffer[i + n] = smpl ;
                }
        }
```

Hope this helps!

**Comment by redned** [comment]
Hey, thanks for that. Unfortunately after playing around with variations of the code you posted, the only sound I'm getting are clicks when I press and release the keys. It sounds like something is wrong inside the fillBuffer method.
