### ISSUE TITLE
Change volume of osc?

### ISSUE THREAD

**Issue by malkomalko** [jussi-kalliokoski/audiolib.js#52]
Hi There,

First off, I'm loving this project I think you have done some amazing work.  I'd love to help document things a little better as a newbie coming into the project, and I can't find how to decrease the output volume of the osc tones.  The volume is VERY loud compared to anything else.  I tried playing around with the Compressor and GainController but I was not able to have much luck.  I'm sure I'm doing something stupid but I've searched with no luck.

Thanks!

**Comment by jussi-kalliokoski** [comment]
Heyo!

Depends on your approach, if you're using `append()` or `getMix()`. If you're using `append()` you can set `osc.mix = 0.5` or so, but otherwise just multiply the samples before you use them `osc.getMix() * 0.5`.

Hope this helps!

Cheers,
Jussi

**Comment by malkomalko** [comment]
Thank ya!
