### ISSUE TITLE
Load mp3 into sampler?

### ISSUE THREAD

**Issue by malkomalko** [jussi-kalliokoski/audiolib.js#53]
Me again :).. was reading some posts saying that this may happen in the future.  Just wanted to know if this is possible now or if you would like help to make it happen.  I think being able to load up smaller files would be a big win.  Even short one off wavs are 100-150k, and increase in size when turned into a base64 string.

**Comment by jussi-kalliokoski** [comment]
Not possible yet, but we're working on this as fast as we can! ;) If you want to help, [aurora.js](https://github.com/JensNockert/aurora.js) is something we're trying to build a little bit of community around, so you're welcome to hang out in #aurora-js on freenode IRC. :)

**Comment by malkomalko** [comment]
cool.. I'm hanging out there now

On Sun, Mar 18, 2012 at 4:27 AM, Jussi Kalliokoski <
reply@reply.github.com

**Comment by jussi-kalliokoski** [comment]
This functionality will not be implemented in audiolib.js at this stage, sorry. :( Closing.
