### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by markbr** [jussi-kalliokoski/audiolib.js#66]
Hey, I have a synth I put together using audiolib that I'd like to add to Github. It's not hosted anywhere at the moment but will be soon. I'm new to Github so do I just add it and put a link to the audiolib page in the about section?

As soon as it is hosted somewhere, I will send you a link to add it to the demo section. It's not the tidiest code at the moment and comments still have to be added.

**Comment by jussi-kalliokoski** [comment]
Hello there!

Excellent news! You can just put the link up here and I'll publish it in relevant places. Keep up the great work!

Jussi

**Comment by markbr** [comment]
Sorry for late reply. The demo can be seen at http://www.pungostudios.com/spraoidev/gossamer/index.html

This link may or may not change. If it does I will let you know.

**Comment by jussi-kalliokoski** [comment]
Cool stuff! If you make a PR for adding this to the demos, I'll gladly accept! (Sorry for not reacting for a year...)
