### ISSUE TITLE
Implement All Pass Filter

### ISSUE THREAD

**Issue by jussi-kalliokoski** [jussi-kalliokoski/audiolib.js#7]
All Pass Filter needed.

**Comment by davidgovea** [comment]
3 Biquad Filters (All-pass, high-pass, low-pass) and fancy test page:
25a159475e8e88006877
Didn't want to pull request this just yet - I structured it a bit weird. Let me know what you think

BiquadFilter is the parent, and BiquadFilter.[HighPass/LowPass/AllPass] calculates the coefficients and creates a BiquadFilter.  Kinda weird structure - I was just messing around today trying to build a reverb effect & I saw that your AllPass is just a basic n-sample delay.

**Comment by jussi-kalliokoski** [comment]
Double implemented!
