### ISSUE TITLE
Using in Firefox Addon SDK as a module?

### ISSUE THREAD

**Issue by ali-mi** [jussi-kalliokoski/audiolib.js#71]
Is it possible to use audiolib.js as a module in Firefox Addon SDK (I am using Addon Builder) so that I can call it from an extension script, e.g. using require("....") from main.js? Normally if it works for Node, I assume that should work as well, but could not figure out which files to put in which location. Any help on this would be appreciated.

**Comment by jussi-kalliokoski** [comment]
Hello! Sorry for the delay on this.

Yes, I believe it should be possible, but I haven't tried. audiolib.js is compatible with node without depending on any of it's specific APIs so I'd assume CommonJS require would work elsewhere as well. If not, please file an issue on that. ;)

You should probably just try downloading the [latest version](https://github.com/jussi-kalliokoski/audiolib.js/downloads) and including that. Assuming you're using require:

``` javascript

var audioLib = require('./PATH/TO/audiolib.js')

```

And then everything _should_ work as it normally would. But if it doesn't, again, please file an issue! :)

Cheers,
Jussi
