### ISSUE TITLE
npm installation failed on Ubuntu 

### ISSUE THREAD

**Issue by NHQ** [jussi-kalliokoski/audiolib.js#73]
Node version 0.8.6

$ npm install audiolib
...
...
File "lib/audiolib.js" created.

Done, without errors.
npm http GET https://registry.npmjs.org/cubeb
npm http 304 https://registry.npmjs.org/cubeb

> cubeb@0.1.2 install /home/nhq/development/barn/node_modules/audiolib/node_modules/cubeb
> node-gyp rebuild

make: Entering directory `/home/nhq/development/barn/node_modules/audiolib/node_modules/cubeb/build'
  CXX(target) Release/obj.target/node-cubeb/src/common.o
  CXX(target) Release/obj.target/node-cubeb/src/constants.o
../src/constants.cpp:4:25: fatal error: cubeb/cubeb.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/node-cubeb/src/constants.o] Error 1
make: Leaving directory`/home/nhq/development/barn/node_modules/audiolib/node_modules/cubeb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:215:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! System Linux 3.2.0-32-generic-pae
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nhq/development/barn/node_modules/audiolib/node_modules/cubeb
gyp ERR! node -v v0.8.6
gyp ERR! node-gyp -v v0.6.3
gyp ERR! not ok 
npm ERR! cubeb@0.1.2 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the cubeb@0.1.2 install script.
npm ERR! This is most likely a problem with the cubeb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls cubeb
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-32-generic-pae
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "audiolib"
npm ERR! cwd /home/nhq/development/barn
npm ERR! node -v v0.8.6
npm ERR! npm -v 1.1.48
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nhq/development/barn/npm-debug.log
npm ERR! not ok code 0

**Comment by NHQ** [comment]
I guess its b/c I don't have cubeb installed

**Comment by knappe** [comment]
@NHQ Did you ever figure out how to get cubeb installed?  I've contacted the maintainer of cubeb since it looks to be a platform independent problem:

https://github.com/jussi-kalliokoski/audiolib.js/issues/79

**Comment by psirenny** [comment]
+1

**Comment by LVsam** [comment]
+1

**Comment by jussi-kalliokoski** [comment]
Just published the latest version on npm and at least on Arch with node 0.10.15 it works. If there's a problem with the cubeb install, please file a bug against [jussi-kalliokoski/node-cubeb](https://github.com/jussi-kalliokoski/node-cubeb/issues)
