### ISSUE TITLE
Mobile Safari support?

### ISSUE THREAD

**Issue by JackCA** [jussi-kalliokoski/audiolib.js#76]
Is anyone aware of a technique for getting audiolib.js to work in mobile safari (iOS)?

**Comment by jussi-kalliokoski** [comment]
If create the Sink instance in an event handler that responds to a touch event, it should do the trick. Unfortunately I can't test so I'm not sure.

P.S. Sorry for late response!

**Comment by JackCA** [comment]
Thanks! I'll give that a shot

**Comment by jussi-kalliokoski** [comment]
Assuming the trick works; Closing.
