### ISSUE TITLE
Include a build please

### ISSUE THREAD

**Issue by tiborsaas** [jussi-kalliokoski/audiolib.js#77]
Hello,

I don't want to mess with grunt, it fails on windows anyways. Please commit a build file, it is not such a big deal. 

Thanks.

**Comment by jussi-kalliokoski** [comment]
Done. For npm, build happens now in prepublish phase, as for browser builds, now there's a branch containing the downloadable versions: https://github.com/jussi-kalliokoski/audiolib.js/tree/downloads
