### ISSUE TITLE
Implement Reverb / Convolution

### ISSUE THREAD

**Issue by jussi-kalliokoski** [jussi-kalliokoski/audiolib.js#8]
Want! As many algorithms as possible.

**Comment by davidgovea** [comment]
doink #27

**Comment by jussi-kalliokoski** [comment]
Yay!! Will keep the issue open until 0.5.0

**Comment by davidgovea** [comment]
What sort of release timeframe do you have in mind?

**Comment by jussi-kalliokoski** [comment]
Not sure yet, I'm hoping to release on 12.08., but if that becomes impossible, I'll have to delay it. I'm trying to pack as many of the upcoming non-backwards-compatibilities to the v.0.5.0, and I'm hoping the main parts of the API are stable by then. Which brings us back to questions in #3 .

**Comment by jussi-kalliokoski** [comment]
I think the Freeverb algorithm is quite good for a core component, the rest should probably be made plugins.

**Comment by davidgovea** [comment]
I've reviewed the multichannel effect changes.. looking good!  I'll be refactoring freeverb to use the new setParam format for changing room size and such.

**Comment by jussi-kalliokoski** [comment]
Cool! So, yes, the setParam is part sugar, part hopeful optimization, due to the fact that you can just override it in the prototype when the effect has dynamic features.

**Comment by davidgovea** [comment]
Updated freeverb, but it's sounding kinda metallic and quiet compared to the first version.  I'll be bug hunting soon
e1ea5548fafb59bf46d3
7c7a405d9085d1a33922
8a47e36fe42a39473cde

**Comment by jussi-kalliokoski** [comment]
Looks good to me, closing.
