### ISSUE TITLE
Can audiolib.js work with webRTC?

### ISSUE THREAD

**Issue by SnowOnion** [jussi-kalliokoski/audiolib.js#81]
Well... I want to get the spectrum of real-time audio stream from microphone input.
Now I get the microphone input with webRTC:
`navigator.getMedia ( {audio: true}, 
   function(mediaStream) {
      // Successful callback, process the mediaStream coming from microphone
      });
`
I tried the Web Audio API way, using AudioContext and Analyser to do the spectrum analysis. However, it works well on PC's Chrome 29, but doesn't work on Android's Chrome 29 or Chrome Beta 30 (relative flags enabled) (WebRTC itself works well.) . After some try, I decided not to use Web Audio API, but use audiolib.js instead.

And here comes the point=.= 
I've learned how to process the audio produced by Oscillator in audiolib.js, but I don't know how to process real-time audio stream with audiolib.js. How to connect audiolib.js and webRTC?

Thanks ^.^

**Comment by jussi-kalliokoski** [comment]
There's no inherent issue preventing it from working with WebRTC. That said, there's no built-in way of doing that either (nor will there be for now).

I don't have the time to try it out right now, but probably the best way to interface with WebRTC is via the ScriptProcessorNode (theoretical code, written against the current spec):

``` javascript
var context = new AudioContext();
var scriptNode = context.createScriptProcessor();
var streamNode;

scriptNode.onaudioprocess = function (event) {
  var leftInput = event.inputBuffer.getChannelData(0);
  var rightInput = event.inputBuffer.getChannelData(1);
  var leftOutput = event.inputBuffer.getChannelData(0);
  var rightOutput = event.inputBuffer.getChannelData(1);
  // Process buffers with audiolib.js
};

navigator.getMedia({ audio: true }, function (mediaStream) {
  streamNode = context.createMediaStreamSource(mediaStream);
  streamNode.connect(scriptNode);
  scriptNode.connect(context.destination);
});
```

**Comment by jussi-kalliokoski** [comment]
Closing the issue, please reopen if this doesn't work. :)
