### ISSUE TITLE
Implement better / more Delay methods.

### ISSUE THREAD

**Issue by jussi-kalliokoski** [jussi-kalliokoski/audiolib.js#9]
Maybe as plugins?

**Comment by jussi-kalliokoski** [comment]
Rewrote Delay to have a single algorithm (previously algo0) and spiced it up with some extra functions to provide the old functionality of algo1 and more. Review, please.

**Comment by davidgovea** [comment]
Not a complete review, but I found a typo: #19

Will review once I explore a bit more.

**Comment by jussi-kalliokoski** [comment]
I'd say it's working okay, closing! ^^
